//! typio-host — the Wayland input-method host for Typio.
//!
//! This crate owns the shipping host daemon and its subsystem tests. Earlier
//! C implementations are referenced in module docs only as porting history.
//!
//! ## Current modules
//!
//! - [`engine_loader`] discovers `typio-engine-*.toml` manifests, parses them
//!   with the `toml` crate, negotiates capabilities, and registers
//!   out-of-process engine backends with libtypio.
//! - [`config_watcher`] watches the config directory and engine-manifest
//!   subdirectory via inotify, filters events to relevant files, and debounces
//!   reload triggers with a one-shot timerfd.

// Auto-generated by build.rs.
pub mod build_info {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/build_info.rs"));
}

pub mod app;
pub mod backoff;
pub mod boundary;
pub mod candidate_guard;
pub mod config_watcher;
pub mod engine_loader;
pub mod focus_controller;
pub mod health;
pub mod icon_badge;
pub mod indicator;
pub mod input_method;
pub mod ipc;
pub mod ipc_bus;
pub mod keyboard;
pub mod keyboard_policy;
pub mod language_display;
pub mod notifier;
pub mod panel;
pub mod panel_coordinator;
pub mod panel_scheduler;
pub mod preedit;
pub mod protocols;
pub mod pw_capture;
pub mod repeat_timer;
pub mod resume_signal;
pub mod service;
pub mod session_glue;
pub mod startup_guard;
pub mod state_controller;
pub mod text_ui_state;
pub mod tray_menu;
pub mod tray_sni;
pub mod uds_server;
pub mod watchdog;
