//! Build script for typio-host.
//!
//! Emits Cargo build-time constants for version, install paths, and feature
//! switches.

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let project_root = manifest_dir.parent().unwrap().parent().unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Version from Cargo package metadata.
    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let mut version_parts = version.split('.');
    let major = version_parts.next().unwrap_or("0");
    let minor = version_parts.next().unwrap_or("0");
    let patch = version_parts.next().unwrap_or("0");

    // Source label: git describe --always --dirty --tags, or "source" fallback.
    let source_label = Command::new("git")
        .args(["describe", "--always", "--dirty", "--tags"])
        .current_dir(project_root)
        .output()
        .ok()
        .and_then(|o| {
            if o.status.success() {
                Some(String::from_utf8_lossy(&o.stdout).trim().to_string())
            } else {
                None
            }
        })
        .unwrap_or_else(|| "source".to_string());

    // Install paths. Cargo sets CARGO_CFG_* for target but not for install
    // prefix. Use environment overrides first, then GNU-style defaults.
    let prefix = env::var("TYPIO_INSTALL_PREFIX").unwrap_or_else(|_| "/usr/local".to_string());
    let bindir = env::var("TYPIO_INSTALL_BINDIR").unwrap_or_else(|_| format!("{prefix}/bin"));
    let libdir = env::var("TYPIO_INSTALL_LIBDIR").unwrap_or_else(|_| format!("{prefix}/lib"));
    let datadir = env::var("TYPIO_INSTALL_DATADIR").unwrap_or_else(|_| format!("{prefix}/share"));

    let engine_dir = format!("{datadir}/typio/engines");
    let data_dir = format!("{datadir}/typio");
    let install_icon_dir = format!("{datadir}/icons");
    let source_icon_dir = project_root
        .join("data/icons")
        .to_string_lossy()
        .into_owned();

    // Feature toggles. Flux tracks wayland.
    let enable_wayland = env::var("CARGO_FEATURE_WAYLAND").is_ok();
    let enable_systray = env::var("CARGO_FEATURE_SYSTRAY").is_ok();
    let enable_voice = env::var("CARGO_FEATURE_VOICE").is_ok();
    let have_flux = enable_wayland;

    // flux-sys publishes the Meson build-tree rpaths it used via `links`
    // metadata. Re-emit them here so typio-host's bins and test harnesses load
    // the same libflux that bindgen saw, not a stale system install.
    if let Ok(rpaths) = env::var("DEP_FLUX_RPATHS") {
        for dir in rpaths.split(';').filter(|s| !s.is_empty()) {
            println!("cargo:rustc-link-arg=-Wl,-rpath,{dir}");
        }
    }

    // Emit env vars for option_env!() consumption at compile time.
    println!("cargo:rustc-env=TYPIO_VERSION={version}");
    println!("cargo:rustc-env=TYPIO_VERSION_MAJOR={major}");
    println!("cargo:rustc-env=TYPIO_VERSION_MINOR={minor}");
    println!("cargo:rustc-env=TYPIO_VERSION_PATCH={patch}");
    println!("cargo:rustc-env=TYPIO_BUILD_SOURCE_LABEL={source_label}");
    println!("cargo:rustc-env=TYPIO_INSTALL_PREFIX={prefix}");
    println!("cargo:rustc-env=TYPIO_INSTALL_BINDIR={bindir}");
    println!("cargo:rustc-env=TYPIO_INSTALL_LIBDIR={libdir}");
    println!("cargo:rustc-env=TYPIO_INSTALL_DATADIR={datadir}");
    println!("cargo:rustc-env=TYPIO_ENGINE_DIR={engine_dir}");
    println!("cargo:rustc-env=TYPIO_DATA_DIR={data_dir}");
    println!("cargo:rustc-env=TYPIO_INSTALL_ICON_DIR={install_icon_dir}");
    println!("cargo:rustc-env=TYPIO_SOURCE_ICON_DIR={source_icon_dir}");
    println!(
        "cargo:rustc-env=HAVE_WAYLAND={}",
        if enable_wayland { "1" } else { "0" }
    );
    println!(
        "cargo:rustc-env=HAVE_SYSTRAY={}",
        if enable_systray { "1" } else { "0" }
    );
    println!(
        "cargo:rustc-env=HAVE_VOICE={}",
        if enable_voice { "1" } else { "0" }
    );
    println!(
        "cargo:rustc-env=HAVE_FLUX={}",
        if have_flux { "1" } else { "0" }
    );

    // Generate a Rust module with the same values for convenient `use`.
    let build_info = format!(
        "/// Auto-generated build-time constants.\n\
         // This file is generated by crates/typio-host/build.rs.\n\
         pub const TYPIO_VERSION: &str = \"{version}\";\n\
         pub const TYPIO_VERSION_MAJOR: &str = \"{major}\";\n\
         pub const TYPIO_VERSION_MINOR: &str = \"{minor}\";\n\
         pub const TYPIO_VERSION_PATCH: &str = \"{patch}\";\n\
         pub const TYPIO_BUILD_SOURCE_LABEL: &str = \"{source_label}\";\n\
         pub const TYPIO_INSTALL_PREFIX: &str = \"{prefix}\";\n\
         pub const TYPIO_INSTALL_BINDIR: &str = \"{bindir}\";\n\
         pub const TYPIO_INSTALL_LIBDIR: &str = \"{libdir}\";\n\
         pub const TYPIO_INSTALL_DATADIR: &str = \"{datadir}\";\n\
         pub const TYPIO_ENGINE_DIR: &str = \"{engine_dir}\";\n\
         pub const TYPIO_DATA_DIR: &str = \"{data_dir}\";\n\
         pub const TYPIO_INSTALL_ICON_DIR: &str = \"{install_icon_dir}\";\n\
         pub const TYPIO_SOURCE_ICON_DIR: &str = \"{source_icon_dir}\";\n\
         pub const HAVE_WAYLAND: bool = {wayland};\n\
         pub const HAVE_SYSTRAY: bool = {systray};\n\
         pub const HAVE_VOICE: bool = {voice};\n\
         pub const HAVE_FLUX: bool = {flux};\n",
        version = version,
        major = major,
        minor = minor,
        patch = patch,
        source_label = escape_str(&source_label),
        prefix = escape_str(&prefix),
        bindir = escape_str(&bindir),
        libdir = escape_str(&libdir),
        datadir = escape_str(&datadir),
        engine_dir = escape_str(&engine_dir),
        data_dir = escape_str(&data_dir),
        install_icon_dir = escape_str(&install_icon_dir),
        source_icon_dir = escape_str(&source_icon_dir),
        wayland = enable_wayland,
        systray = enable_systray,
        voice = enable_voice,
        flux = have_flux,
    );
    std::fs::write(out_dir.join("build_info.rs"), build_info).unwrap();

    // Rerun-if-changed guards: rebuild when these change.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=TYPIO_INSTALL_PREFIX");
    println!("cargo:rerun-if-env-changed=TYPIO_INSTALL_BINDIR");
    println!("cargo:rerun-if-env-changed=TYPIO_INSTALL_LIBDIR");
    println!("cargo:rerun-if-env-changed=TYPIO_INSTALL_DATADIR");
    println!("cargo:rerun-if-env-changed=TYPIO_ENGINE_DIR");
    println!("cargo:rerun-if-env-changed=DEP_FLUX_RPATHS");
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
